base/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from .api import api
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('blog/', include('blog.urls')),
    path('', views.index, name='index'),
    path('api/', api.urls),
]

blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns =[
    path('<int:user_id>/post/',views.blog_post,name="post_blog"),
    path('<int:blog_id>/detail/',views.blog_detail,name="blog"),
    path("<int:blog_id>/article/<int:article_id>/view",views.article_view,name="view"),
    path("<int:blog_id>/article/edit",views.article_edit,name="edit"),
    path("<int:blog_id>/article/<int:article_id>/comment",views.comment_edit,name="comment"),
    path("todo/",views.todo,name="todo"),
]

base/models.py
from django.db import models
from django.utils import timezone

class SoftDeleteManager(models.Manager):
    use_for_related_fields = True

    def get_queryset(self):
        return super().get_queryset().filter(deleted_at__isnull=True,status=0)
    
    
class SoftDeleteModel(models.Model):
    
    deleted_at = models.DateTimeField('삭제일', null=True, default=None)
    status = models.PositiveIntegerField('상태코드',default=0)
    class Meta:
        abstract = True  # 상속 할수 있게 

    objects = SoftDeleteManager()  # 커스텀 매니저 

    def delete(self, using=None, keep_parents=False):
        self.deleted_at = timezone.now()
        self.save(update_fields=['deleted_at'])

    def restore(self):  # 삭제된 레코드를 복구한다.
        self.deleted_at = None
        self.save(update_fields=['deleted_at'])
        
class TimeMixin(SoftDeleteModel):
    reg_date=models.DateTimeField('등록날짜',auto_now_add=True)
    update_date=models.DateTimeField('수정날짜',auto_now=True,null=True)
    
    class Meta:
        abstract = True
    
    def since(self):
        time = timezone.now()-self.reg_date
        return str(time)
    

blog/models.py
from django.db import models
from django.urls import reverse
from accounts.models import User
from base.models import *


class Blog(TimeMixin):
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name='blog')
    name = models.CharField('블로그이름',max_length=50)
# Create your models here.
    
class HashTag(models.Model):
    name = models.CharField('해시태그',max_length=20)
    
class Article(TimeMixin):
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name='articles')
    blog = models.ForeignKey(Blog,on_delete=models.CASCADE,related_name='articles')
    title = models.CharField('제목',max_length=50)
    context = models.TextField('내용')
    image = models.ImageField('이미지',upload_to="article/img/%Y/%m/%d",blank=True,null=True)
    tags = models.ManyToManyField(HashTag,related_name="articles",blank=True)
    status = models.SmallIntegerField('상태',default=0,null=True,blank=True)
    @classmethod
    def get_articles(cls,**kwargs):
        result = cls.objects.filter()
        return result
    def save(self,*args, **kwargs):
        super().save(*args, **kwargs)
        SaveHistory.objects.create(article=self)
    def __str__(self):
        return self.title
    @property
    def get_absolute_url(self):
        return reverse('blog:view',kwargs={'blog_id':self.blog_id,'article_id':self.pk})
class SaveHistory(models.Model):
    saved_date = models.DateTimeField(auto_now=True)
    article = models.ForeignKey(Article,on_delete=models.CASCADE,related_name='savehistories')
class Comment(TimeMixin):
    username = models.CharField('게시자',max_length=20,null=True,blank=True)
    password = models.CharField('비밀번호', max_length=128,null=True,blank=True)
    parent = models.ForeignKey('self',on_delete=models.CASCADE,related_name='childs',null=True,blank=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name='comment',null=True,blank=True)
    article = models.ForeignKey(Article,on_delete=models.CASCADE,related_name="comment")
    context = models.TextField('내용')
    
    @property
    def get_absolute_url(self):
        return reverse('blog:view',kwargs={'blog_id':self.article.blog_id,'article_id':self.article_id})
class Todo(TimeMixin):
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name='todo')
    context = models.CharField('할일',max_length=50)

blog/forms.py
from django import forms
from .models import *

class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['name']

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title','context']
        
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['context']
        
class TodoForm(forms.ModelForm):
    class Meta:
        model = Todo
        fields = ['context']

base/views.py
from django.shortcuts import redirect, render
from django.contrib import messages
from base.functions import auto_login
from blog.models import Blog
from base.functions import timer
@timer#
def index(request):
    blogs = Blog.objects.all()
    context={"blogs":blogs}
    if request.user.is_authenticated:
        if request.user.blog.all().exists():
            context.update(blog=Blog.objects.get(user=request.user))
    return render(request,'index.html',context)

blog/views.py
from datetime import datetime, timedelta
from django.utils.functional import cached_property
from django.utils import timezone
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib import messages
from django.db.models import *
from django.core.paginator import Paginator
from blog.forms import *
from blog.models import Blog
from base.functions import *
from base.const import *
# Create your views here.

@timer
def blog_post(request,user_id):
    user = User.objects.get(pk=user_id)
    if request.method == "POST":
        form = BlogForm(request.POST)
        blog = form.save(commit=False)
        blog.user = user
        blog.reg_date = timezone.now()
        blog.save()
    return redirect('index')

def dayoffset():
    result = 5 - datetime.now().timetuple()[6]
    if result < 0:
        result = 6-result
    return result-5

def daydelta(a):
    now = datetime.now()
    result:datetime = a
    c = now - result
    return c.days #+ dayoffset()

@timer
def blog_detail(request,blog_id):
    page = request.GET.get('page')
    context={}
    blog = Blog.objects.get(pk=blog_id)
    articles = Article.objects.filter(blog=blog).exclude(status=DELETED,tags__name="과제")
    tag = request.GET.get('hashtag')
    if tag:
        articles = get_hashtag_articles(articles,tag)
    grasses = articles.values('reg_date','update_date').filter(reg_date__gte=datetime.now()-timedelta(days=365))
    articles=articles.exclude(tags__name="과제")
    dates = list(map(lambda x : daydelta(x['reg_date']),grasses))    
    histories = articles.select_related('savehistories').annotate(saved_date = F('savehistories__saved_date')).values('saved_date').filter(saved_date__isnull=False)
    dates += list(map(lambda x : daydelta(x['saved_date']),histories))
    t_d = {}
    for i in dates:
        #1일전 1일전 5일전 6일전 7일전 7일전식으로 모여있음. dict로 카운트해줌.
        t = str(i)
        if not t_d.get(t):
            t_d[str(i)]=1
        else:
            t_d[str(i)]+=1
    t_list=list(t_d.items())
    pages = Paginator(articles.order_by('-reg_date'),21)
    context.update(blog=blog)
    context.update(articles=pages.get_page(page))
    context.update(dates=t_list)
    return render(request,'blog/main.html',context)

#@cached_property
def get_hashtag_articles(articles:QuerySet,name):
    return articles.filter(tags__name=name)
    
    
    # return HashTag.objects.filter(name=name).prefetch_related('articles').annotate(title=F('articles__title'),context=F('articles__context'),pk=F('articles__pk'),status=F('articles__status'),reg_date=F('articles__reg_date'),update_date=F('articles__update_date')).exclude(status=status).values()

@timer
def article_view(request,blog_id,article_id):
    context = {}
    blog = Blog.objects.get(pk=blog_id)
    article = Article.objects.get(pk=article_id)
    if article.status == DELETED:
        messages.warning(request,'삭제된 게시물입니다')
        return redirect('index')
    context.update(article=article)
    context.update(blog=blog)
    context.update(comments=article.comment.filter(parent__isnull=True))
    print(article.comment.all())
    return render(request,'blog/detail_view.html',context)

def article_edit(request,blog_id):
    context={}
    user = request.user
    blog = Blog.objects.get(pk=blog_id)
    context.update(user=user)
    context.update(blog=blog)
    action = request.GET.get('type')
    if request.method=="POST" and blog.user ==user:   
        article_id = request.GET.get('article_id')
        if action =="post":
            form:ArticleForm = ArticleForm(request.POST)
            if form.is_valid():
                article = form.save(commit=False)
                article.user = user
                article.blog = blog
                article.reg_date= timezone.now()
                article.save()
                tags_setter(request,article)
                return JsonResponse({'message':'201','type':'created','article_id':article.pk})
        elif action=="delete":
            article =Article.objects.get(pk=article_id,user=user,blog=blog)
            article.status=DELETED
            article.save()
            #article.delete()
            messages.success(request,"success")
            return redirect('blog:blog',blog_id)
        
        elif action =="update":
            article:Article =Article.objects.get(pk=article_id,user=user,blog=blog)
            form:ArticleForm = ArticleForm(request.POST,instance=article)
            if form.is_valid():
                article=form.save(commit=False)
                article.update_date=timezone.now()
                tags_setter(request,article)  
                return JsonResponse({'message':'201','type':'updated','article_id':article.pk})
            context.update(hashtags = article.tags.all())
            context.update(form=form)
            context.update(article=article)
            test = article.tags.all()
            return render(request,'blog/edit_view.html',context)
        return render(request,'blog/edit_view.html',context)
    messages.warning(request,"권한이없어요")
    return redirect('blog:blog',blog_id)
        
def tags_setter(request,article):
    article.tags.clear()
    tags = tag_joiner(request.POST.get('tags'))
    if tags:
        for i in tags:
            article.tags.add(HashTag.objects.get_or_create(name=i)[0])
    article.save()              
    
def comment_edit(request,blog_id,article_id):
    context = {}
    blog = Blog.objects.get(pk=blog_id)
    article = Article.objects.get(pk=article_id)
    action = request.GET.get('type')
    context.update(blog_id=blog_id)
    context.update(article_id=article_id)
    username = request.POST.get('username')
    password = request.POST.get('password')
    if request.method == "POST":
        if action == "post":    
            form:CommentForm = CommentForm(request.POST)
            if form.is_valid():
                comment = form.save(commit=False)
                if request.user.is_authenticated:
                    comment.user = request.user
                else:
                    if username and password:
                        comment.username = username
                        comment.password = password
                    else:
                        messages.warning(request,"ID와 비밀번호를 입력해주세요")
                        return redirect('blog:view',blog_id,article_id)
                        
                parent = request.GET.get('parent')
                if parent:
                    print('ihaveparent',parent)
                    parent = Comment.objects.get(pk=parent)
                    comment.parent = parent
                else:
                    print("ihavenoparent")
                comment.article = article
                comment.save()
                print("valid")
        elif action == "delete":
            if request.user.is_authenticated:
                comment = Comment.objects.get(pk=request.GET.get('comment'),user=request.user)
                comment.delete()
            else:
                if username and password:
                    try:
                        comment = Comment.objects.get(username=username,password=password)
                        comment.delete()
                    except:
                        messages.warning(request,"ID와 비밀번호를 확인해주세요")
                        return redirect('blog:view',blog_id,article_id)
                
    return redirect('blog:view',blog_id,article_id)

def todo(request):
    action = request.GET.get('action')
    todo_id = request.GET.get('todo_id')
    if todo_id:
        todo = Todo.objects.get(pk=todo_id)
    if request.method=="POST":
        if action=="post":
            form = TodoForm(request.POST)
            if form.is_valid():                  
                    
                todo = form.save(commit=False)
                todo.user = request.user    
            else:
                messages.warning(request,'내용을 입력해주세요')   
                return redirect(request.META.get('HTTP_REFERER','root'))              
        elif action=="done":
            todo.status = 2
        elif action=="delete":
            todo.status = 1
        todo.save()
    return redirect(request.META.get('HTTP_REFERER','root'))

base/templates/blog/detail_view.html
{% extends 'blog/layout.html' %}
{% block article_meta %}
{{article.context|json_script:"context"}}
{% endblock %}
{% block article_layout %}
<div class="article detail">
    {% if request.user.is_authenticated %}
    <form action="{% url 'blog:edit' blog.pk %}?article_id={{article.pk}}&type=update" method="post">
        {% csrf_token %}
        <button type="submit">수정</button>        
    </form>
    {% endif %}
    {% if article %}
    <div class="article title">
        {{article.title}}
    </div>
    <div class='article tags'>
        {% for tag in article.tags.all %}
        <span> #{{tag.name}}</span>
        {% endfor %}
    </div>
    <div class="article date">
       게시 : {{article.reg_date}}
    </div>
    {% if article.update_date %}
    <div class="article date">
       수정 : {{article.update_date}}
    </div>
    {% endif %}
    {% endif %}
    <div class='toast-ui-viewer'></div>
    
    {% if request.user.is_authenticated %}
    <form action="{% url 'blog:edit' blog.pk %}?article_id={{article.pk}}&type=delete" method="post">
        {% csrf_token %}
        <button type="submit">글삭제</button>        
    </form>
    {% endif %}
    <div>
    {% for comment in comments %}
        <div>
            <div class="comment-owner">작성자 : 
                {% if comment.user %}
                {{comment.user}}
                {% else %}
                {{comment.username}}
                {% endif %}
            </div>
            <div>{{comment.context}}</div>
            <form action="{% url 'blog:comment' blog.pk article.pk %}?type=delete&comment={{comment.pk}}" method="post">
                {%csrf_token%}
                <button type="submit">댓글삭제</button>
            </form>
        </div>
        {% for recomment in comment.childs.all %}
        <div class="re">
            <div class="comment-owner">작성자 : 
                {% if comment.user %}
                {{comment.user}}
                {% else %}
                {{comment.username}}
                {% endif %}
            </div>
            <div>{{comment.context}}</div>
            <form action="{% url 'blog:comment' blog.pk article.pk %}?type=delete&comment={{comment.pk}}" method="post">
                {%csrf_token%}
                <button type="submit">댓글삭제</button>
            </form>
        </div>
        {% endfor %}
        <form class = "re comment-form"action="{% url 'blog:comment' blog.pk article.pk %}?type=post&parent={{comment.pk}}" method = "post">
            {% csrf_token %}    
            {% if request.user.is_authenticated %}
            <div class="button">{{request.user.username}}</div>
            {% else %}
            <div class="unauthen">
                <input class="half"placeholder="이름을입력해주세요"type="text" name="username" autocomplete=false>
                <input class="half"placdholder="비밀번호를입력해주세요" type="password" name="password" autocomplete=false>
            </div>
            {% endif %}
            <input type="text" name="context" placeholder="댓글을 적어주세요" autocomplete=false>
            
            <button type="submit">대댓글등록</button> 
        </form>
        {% endfor %}
    </div>



    <form class = "comment-form"action="{% url 'blog:comment' blog.pk article.pk %}?type=post" method = "post">
        {% csrf_token %}    
        {% if request.user.is_authenticated %}
        <div class="button">{{request.user.username}}</div>
        {% else %}
        <div class="unauthen">
            <input class="half"placeholder="이름을입력해주세요"type="text" name="username" autocomplete=false>
            <input class="half"placdholder="비밀번호를입력해주세요" type="password" name="password" autocomplete=false>
        </div>
        {% endif %}
        <input type="text" name="context" placeholder="댓글을 적어주세요" autocomplete=false>
        
        <button type="submit">댓글등록</button> 
    </form>
</div>
{% endblock %}
{% block article_footer %}
{% include 'blog/src/toastui_js.html' %}
{% endblock%}

base/templates/blog/edit_view.html
{% extends 'blog/layout.html' %}
{% block article_meta %}
{% endblock %}

{% block article_layout %}
    <form method="post" onsubmit="article_post(this);return false;">
        {% csrf_token %}
        <input type="text" name="title" placeholder="제목을 입력해주세요"
            value="{{article.title|default_if_none:''}}"
        >
        <button type="submit">저장</button>
    </form>
    <form action="" onsubmit="return false;">
        
        <input class = "hash_input" type="text" name='tags' placeholder="태그를 입력해주세요 #python"
        value="{% for tag in hashtags %}#{{tag.name}} {% endfor %}">
    </form>
    <div class="toast-ui-editor"></div>
    {% autoescape on %}
    {{article.context|safe|json_script:"context"}}
    {% endautoescape %}
{% endblock %}
{% block article_footer %}
{% include 'blog/src/toastui_js.html' %}
<script>
    $(window).keypress(function(event) {
      if (!(event.which == 115 && event.ctrlKey) && !(event.which == 19)) return true;
      alert("Ctrl-S pressed");
      event.preventDefault();
      return false;
  });
  </script>
{% endblock %}

{% comment %} 
"{% url 'accounts:kakao_signin' %}?next={{request.path}}"
{% endcomment %}

base/templates/blog/layout.html
{% extends 'layout.html'%}
{% block meta %}
{% include 'blog/src/toastui_meta.html' %}
    {% block article_meta %}
    {% endblock %}
{% endblock %}
{% block layout %}
    {% block article_layout %}

    {% endblock %}
{% endblock %}

{% block footer %}
    {% block article_footer %}

    {% endblock %}
{% endblock %}

base/templates/blog/main.html
{% extends 'layout.html' %}
{% block article_meta %}

{% endblock %}
{% block layout %}
Contribute
<div class="grass-con">
    <div class="grass-table">
        <div class='grass-month'>
            <div></div>
            {% for i in 12|reverse_ranges %}
            <div>{{i|monthdelta}}</div>
            {% endfor %}
        </div>
        {% for i in 7|reverse_ranges %}
        <div class="grass-row">
            <div class="grass-day ellip">{{i|grass_day}}</div>
            {% for j in 52|ranges %}
            <div class="grass grass-{{j|days|weeks:i|match:dates}} grass-select"
            serial="{{j|days|weeks:i|get_date}}"
            data="{{j|days|weeks:i}}"
            count="{{j|days|weeks:i|contribute:dates}}">
            </div>
            {% endfor%}
        </div>
        {% endfor %}
    </div>
    <div id="div-view"></div>
</div>

<div class="post-con">
{% if articles %}
{% for article in articles %}
<div class="post-card">
    <a class = "ellip" href="{% url 'blog:view' blog.pk article.pk %}">{{article.title}}
    </a>
    <div>{{article.context|truncatesmart:300}}</div>
</div>
{% endfor %}
{% endif %}
</div>
<!-- 페이징처리 시작 -->
<div>
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if articles.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ question_list.previous_page_number }}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in articles.paginator.page_range %}
            {% if page_number == articles.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if articles.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ articles.next_page_number }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
</div>
<!-- 페이징처리 끝 -->
{% endblock %}
{% block footer %}
<script>
$('.grass-select').mouseover(function(e) {
    var divTop = e.clientY-80 ;
    var divLeft = e.pageX+110;
    var serial = $(this).attr("serial");
    var count = $(this).attr("count");
    $('#div-view').empty().append(`
    <div style="position:absolute;top:5px;right:5px;width:200px;height:50px;">    
        ${serial}<br>${count}회    
    </div>`);
        $('#div-view').css({ "top": divTop ,"left": divLeft , "position": "absolute" }).show();
        $('#div-view').mouseover(function(){document.getElementById('div-view').style.display='none'});

    });

</script>
{% endblock%}