accounts/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = "accounts"
urlpatterns = [
    path('idfinder/',views.idfinder,name='idfinder'),
    path('signin/',views.signin,name='signin'),
    path('signup/',views.signup,name='signup'),
    path('signout/',views.signout,name='signout'),
]

base/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from .api import api
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('blog/', include('blog.urls')),
    path('', views.index, name='index'),
    path('api/', api.urls),
]

blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns =[
    path('<int:user_id>/post/',views.blog_post,name="post_blog"),
    path('<int:blog_id>/detail/',views.blog_detail,name="blog"),
    path("<int:blog_id>/article/<int:article_id>/view",views.article_view,name="view"),
    path("<int:blog_id>/article/edit",views.article_edit,name="edit"),
    path("<int:blog_id>/article/<int:article_id>/comment",views.comment_edit,name="comment"),
    path("todo/",views.todo,name="todo"),
]

base/models.py
from django.db import models
from django.utils import timezone

class SoftDeleteManager(models.Manager):
    use_for_related_fields = True

    def get_queryset(self):
        return super().get_queryset().filter(deleted_at__isnull=True,status=0)
    
    
class SoftDeleteModel(models.Model):
    
    deleted_at = models.DateTimeField('삭제일', null=True, default=None)
    status = models.PositiveIntegerField('상태코드',default=0)
    class Meta:
        abstract = True  # 상속 할수 있게 

    objects = SoftDeleteManager()  # 커스텀 매니저 

    def delete(self, using=None, keep_parents=False):
        self.deleted_at = timezone.now()
        self.save(update_fields=['deleted_at'])

    def restore(self):  # 삭제된 레코드를 복구한다.
        self.deleted_at = None
        self.save(update_fields=['deleted_at'])
        
class TimeMixin(SoftDeleteModel):
    reg_date=models.DateTimeField('등록날짜',auto_now_add=True)
    update_date=models.DateTimeField('수정날짜',auto_now=True,null=True)
    
    class Meta:
        abstract = True
    
    def since(self):
        time = timezone.now()-self.reg_date
        return str(time)
    

base/views.py
from django.shortcuts import redirect, render
from django.contrib import messages
from base.functions import auto_login
from blog.models import Blog
from base.functions import timer
@timer#
def index(request):
    blogs = Blog.objects.all()
    context={"blogs":blogs}
    if request.user.is_authenticated:
        if request.user.blog.all().exists():
            context.update(blog=Blog.objects.get(user=request.user))
    return render(request,'index.html',context)

base/templates/footer.html
<nav>
    <a href="https://github.com/farrar142">Github</a>
    <a href="https://soundcloud.com/sandring-443999826">Soundcloud</a>
</nav>
<p>
    <span></span>
    <span>
        Powered By gksdjf1690@gmail.com
    </span>
</p>

base/templates/form_errors.html
{% if form.errors %}
{% for field in form %}
    {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
        <div class="alert alert-danger">
            <strong>{{ field.label }}</strong>
            {{ error }}
        </div>
    {% endfor %}
{% endfor %}
{% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
    <div class="alert alert-danger">
        <strong>{{ error }}</strong>
    </div>
{% endfor %}
{% endif %}

base/templates/form_erros.html
{% if form.errors %}
{% for field in form %}
    {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
        <div class="alert alert-danger">
            <strong>{{ field.label }}</strong>
            {{ error }}
        </div>
    {% endfor %}
{% endfor %}
{% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
    <div class="alert alert-danger">
        <strong>{{ error }}</strong>
    </div>
{% endfor %}
{% endif %}

base/templates/header.html
<div class="nav-items">
    <a href="{% url 'index' %}">
        메인으로
    </a>
</div>
<div class="nav-items">
    {% if blog %}
    <a href="{% url 'blog:blog' blog.pk %}">
        {{blog.name}}
    </a>
    {% else %}
    블로그에요
    {% endif %}
    {% comment %} <form action="{% url 'index' %}" method="get">
        <input type="text" placeholder="검색을해보자">
    </form> {% endcomment %}
    
</div>
<div class = "nav-items">
{% if request.user.is_authenticated %}
    <a href="{% url 'accounts:signout' %}" method="get">
        로그아웃
    </a>
{% else %}
<a href="{% url 'accounts:signin' %}" method="get">
    로그인
</a>
{% endif %}
</div>

base/templates/index.html
{% extends 'layout.html' %}
{% block layout  %}
{% if request.user.is_authenticated %}
    {% if request.user.blog.all %}
    {% else %}
    현재 블로그가 없어요 만드시겠어요?
    <form class="form" action="{% url 'blog:post_blog' request.user.pk %}" method = "post">
        {% csrf_token %}
        <input name = "name" value="{{form.username.value|default_if_none:''}}"  type="text" placeholder ="블로그이름" autocomplete="off">
        <button type="submit">생성하기</button>
    </form>
    {% endif %}
{% endif %}
<div class="blog-list">
    <p>현재 개설된 블로그 목록이에요</p>
    {% for blog in blogs %}
    <div>
        <a href="{% url 'blog:blog' blog.pk %}">{{blog.name}}</a>
    </div>
    {% endfor %}
</div>

{% endblock %}

base/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- 폰트어썸 -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
  
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <link rel="stylesheet" href="{% static 'aside.css' %}">
    <link rel="stylesheet" href="{% static 'blog.css' %}">
    <link rel="stylesheet" href="{% static 'navbar.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    <script src="//code.jquery.com/jquery.min.js"></script>
    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
    <title>Blog I Use</title>
    {% include 'src/nav_js.html' %}
    {% block meta %}
    {% endblock %}
</head>
<body>
    <div id="root">
        <div id="header"> 
            {% include 'header.html' %}
        </div> 
        <div id="content">  
            {% if messages %}
            <div class="messages">
                {% for message in messages %}
                    <div {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>
                        {{ message.message }} 
                    </div>
                {% endfor %}
            </div>
            {% endif %}
            <section class="section">
                <div id="left" class="t-30">
                    <div class="sticky">
                        {% include 'left.html' %}
                    </div>
                </div>
                <div id="main">
                    {% block layout %}
                    {% endblock %}
                </div>
                <div id="right" class="t-30">
                    <div class="sticky">
                        {% include 'right.html' %}
                    </div>
                </div>
            </section>
        </div>
        <div id="footer">
            {% include 'footer.html' %}
        </div>
    </div>
    {% block footer%}
    {% endblock %}
</body>
</html>

base/templates/left.html
{% load tags %}
{% if blog %}
    <div>태그 목록</div>
    <div class="ellip">
        {% if blog.articles.count %}
        <a class="button"href="{% url 'blog:blog' blog.pk %}">
            전체글 ({{blog|get_valid_articles}})
        </a>
        {% endif %}
    </div>
    {% for tag in blog.id|get_tags %}
    <div class="ellip">
        
        <a class="button"href="{% url 'blog:blog' blog.pk %}?hashtag={{tag.name|urlencode}}" >
            #{{tag.name}} ({{tag.count}})
        </a>
    </div>
    {% endfor %}
{% endif %}

base/templates/right.html
<div class='ellip'>

    {% if request.user.blog.exists %}
    <form action="{% url 'blog:edit' request.user.blog.first.pk %}?type=post" method="post">
        {% csrf_token %}
        <button type="submit">글쓰기</button>
    </form>
    {% endif %}
    <div class="todo-con  none-scroll">
        투두리스트.
        {% if request.user.is_authenticated %}
        <form class="todo-card" action="{% url 'blog:todo' %}?action=post" method="post">
            {% csrf_token %}
            <input type="text" name="context" placeholder="내용을적어주세요">
            <button type="submit">작성</button>
        </form>
        {% for todo in todolist %}
        <div class="todo-card">
            <div class="todo-content none-scroll">
                {{forloop.counter}}, {{todo.context}}
            </div>
            <div class="todo-status">
                <form class="half button"action="{% url 'blog:todo' %}?action=done&todo_id={{todo.pk}}" method="post">
                    {% csrf_token %}
                    <button type="submit ellip">완료</button>
                </form>
                <form class="half button"action="{% url 'blog:todo' %}?action=delete&todo_id={{todo.pk}}"method="post">
                    {% csrf_token %}
                    <button type="submit ellip">삭제</button>
                </form>
            </div>
        </div>
        {% endfor %}
        {% endif %}
    </div>
    <div class="comment-con">
        {% if commentlist %}
        <div>최근댓글이에요</div>
        {% for comment in commentlist %}
        <a class="ellip" href="{{comment.get_absolute_url }}">
            {{forloop.counter}}, {{comment.c_context}}
        </a>
        {% endfor %}
        {% else %}
        <div>댓글이없어요</div>
        {% endif %}
    </div>
</div>