accounts/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = "accounts"
urlpatterns = [
    path('idfinder/',views.idfinder,name='idfinder'),
    path('signin/',views.signin,name='signin'),
    path('signup/',views.signup,name='signup'),
    path('signout/',views.signout,name='signout'),
]

base/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from .api import api
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('blog/', include('blog.urls')),
    path('', views.index, name='index'),
    path('api/', api.urls),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class User(AbstractUser):
    """
    패스워드는 상속
    """
    class Meta:
        db_table = "accounts_user"
    user_id = models.AutoField(primary_key=True)
    username = models.CharField(
        '유저이름',
        max_length=20,
        help_text='20자 이하로 작성해주세요 @/./+/-/_ 를 사용 할 수 있습니다..',
        unique=True
    )
    email = models.EmailField('이메일')

base/models.py
from django.db import models
from django.utils import timezone

class SoftDeleteManager(models.Manager):
    use_for_related_fields = True

    def get_queryset(self):
        return super().get_queryset().filter(deleted_at__isnull=True,status=0)
    
    
class SoftDeleteModel(models.Model):
    
    deleted_at = models.DateTimeField('삭제일', null=True, default=None)
    status = models.PositiveIntegerField('상태코드',default=0)
    class Meta:
        abstract = True  # 상속 할수 있게 

    objects = SoftDeleteManager()  # 커스텀 매니저 

    def delete(self, using=None, keep_parents=False):
        self.deleted_at = timezone.now()
        self.save(update_fields=['deleted_at'])

    def restore(self):  # 삭제된 레코드를 복구한다.
        self.deleted_at = None
        self.save(update_fields=['deleted_at'])
        
class TimeMixin(SoftDeleteModel):
    reg_date=models.DateTimeField('등록날짜',auto_now_add=True)
    update_date=models.DateTimeField('수정날짜',auto_now=True,null=True)
    
    class Meta:
        abstract = True
    
    def since(self):
        time = timezone.now()-self.reg_date
        return str(time)
    

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from accounts.models import User

class UserSignInForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username','password']
        
class UserSignUpForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ['email','username','password1','password2']
        
class IdfinderForm(forms.ModelForm):
    class Meta:
        model = User  # 사용할 모델
        fields = ['email']

accounts/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import login,logout,authenticate
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from base.functions import *
from accounts.forms import *
from .models import User
# Create your views here.
@timer
def signin(request):
    if request.method=="POST":
        form = UserSignInForm(request.POST)
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username = username,password=password)
        print(user)
        if user is not None:
            login(request,user)
            return redirect('index')
        return render(request,'accounts/signin.html',{'form':form})
    form = UserSignInForm()
    return render(request,'accounts/signin.html',{'form':form})
@timer
def signup(request):
    if request.method=="POST":
        form = UserSignUpForm(request.POST)
        if form.is_valid():
            messages.success(request,"here")
            signed_user = form.save()
            login(request,signed_user)
            return redirect('index')
        context = {'form':form}
        return render(request,'accounts/signup.html',context)
    form = UserSignInForm()
    context = {'form':form}
    return render(request,'accounts/signup.html',context)

@login_required
def signout(request):
    logout(request)
    return redirect('index')


def idfinder(request):
    if request.method == 'POST':
        # messages.success(request, request.POST.get('email'))
        email = request.POST.get('email')
        if email == '':
            messages.warning(request,'Email을 입력 해 주세요')
            return render(request, 'accounts/idfinder.html')
        try:
            user = User.objects.get(email=email)
            messages.success(request,f"ID : {user.username}")
        except:
            messages.error(request,'회원 정보가 없어요')
            return render(request, 'accounts/idfinder.html')
        return redirect('accounts:signin')
    return render(request, 'accounts/idfinder.html')

base/views.py
from django.shortcuts import redirect, render
from django.contrib import messages
from base.functions import auto_login
from blog.models import Blog
from base.functions import timer
@timer#
def index(request):
    blogs = Blog.objects.all()
    context={"blogs":blogs}
    if request.user.is_authenticated:
        if request.user.blog.all().exists():
            context.update(blog=Blog.objects.get(user=request.user))
    return render(request,'index.html',context)

base/templates/accounts/idfinder.html
{% extends 'accounts/layout.html' %}
{% block article_layout %}
<div class="container my-3">
    <form method="post" class="post-form" action="{% url 'accounts:idfinder' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <label for="email"></label>
        <input type="email" class="form-control" name="email" id="email"
                value="{{ email|default_if_none:'' }}"
                placeholder="이메일을 입력해주세요">
        <button>id찾기</button>
    </form>
</div>
{% endblock %}

base/templates/accounts/layout.html
{% extends 'layout.html'%}
{% block meta %}
    {% block article_meta %}
    {% endblock %}
{% endblock %}
{% block layout %}
<div id="article">
    <div id='article-inner'>
    {% block article_layout %}

    {% endblock %}
    </div>
</div>
{% endblock %}

{% block footer %}
    {% block article_footer %}

    {% endblock %}
{% endblock %}

base/templates/accounts/signin.html
{% extends 'accounts/layout.html' %}
{% block article_layout %}

<div class="container my-3">
<form class="post-form" action="{% url 'accounts:signin' %}" method = "post">
    {% csrf_token %}
    {% include "form_errors.html" %}
    <label for="username"></label>
    <input id="username"class="form-control" name = "username" value="{{form.username.value|default_if_none:''}}" type="text" placeholder="유저이름" autocomplete="off">

    <label for="password"></label>
    <input id="password"class="form-control" name = "password" type="password" placeholder="비밀번호" autocomplete="off">

    <button>로그인</button>
</form>
<form action="{% url 'accounts:signup' %}" method="get">
    <button>회원가입</button>
</form>
<div class="accounts-finder">
    <a class="half" href="{% url 'accounts:idfinder' %}">ID찾기</a>
    <a class="half" href="">비밀번호찾기</a>
</div>
</div>
{% endblock %}

base/templates/accounts/signup.html
{% extends 'accounts/layout.html' %}
{% block article_layout %}
<form class="form" action="{% url 'accounts:signup' %}" method = "post">
    {% csrf_token %}
    {% include "form_errors.html" %}
    <input name = "username" value="{{form.username.value|default_if_none:''}}"  type="text" placeholder ="유저이름" autocomplete="off">
    <input name = "email" value="{{form.email.value|default_if_none:''}}"  type="text" placeholder ="이메일" autocomplete="off">
    <input name = "password1" type="password"placeholder ="비밀번호" autocomplete="off">
    <input name = "password2" type="password"placeholder ="확인용비밀번호" autocomplete="off">
    <button type="submit">회원가입</button>
</form>
{% endblock %}